# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cseriildii <cseriildii@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/09 15:39:14 by icseri            #+#    #+#              #
#    Updated: 2024/10/30 12:34:50 by cseriildii       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = weapon

SRCS = main.cpp Weapon.cpp HumanA.cpp HumanB.cpp

include ../Makefile