NAME = intern

SRCS = main.cpp \
		Bureaucrat.cpp \
		AForm.cpp \
		MyException.cpp \
		PresidentialPardonForm.cpp \
		RobotomyRequestForm.cpp \
		ShrubberyCreationForm.cpp \
		Intern.cpp \
		tests.cpp

include ../Makefile